### PR TITLE
Place dark theme class names higher up the DOM

### PR DESCRIPTION
**Pull request by medied**
As part of the Wikipedia Preview refactor (https://phabricator.wikimedia.org/T363468), this refactors the dark theme class names placement from `.wikipediapreview` to top level `.wp-popup-container`

### CODE REVIEW

**Review by hueitan — CHANGES_REQUESTED** [review]
This change is great, storybook does use this state for preview, can you look into it?

**Comment by Nikerabbit** [comment]
Please add a message why or what this fixes (see also https://www.mediawiki.org/wiki/Gerrit/Commit_message_guidelines)

Nit pick: I guess you mean tree, not a stack? Or could just say higher up in the DOM.

**Comment by medied** [comment]
> This change is great, storybook does use this state for preview, can you look into it?

You're right, it doens't make sense to keep the color scheme test under the preview storybook now as the classes get set in the container. So I've removed them from the preview storybook and added it under the target storybook, what do you think?

**Comment by medied** [comment]
> Please add a message why or what this fixes (see also https://www.mediawiki.org/wiki/Gerrit/Commit_message_guidelines)
> 
> Nit pick: I guess you mean tree, not a stack? Or could just say higher up in the DOM.

Ah yes: higher up the DOM! PR description updated

**Pull request merged**
