### PR TITLE
T286553 deploy branch into different folder on pages

### PR DESCRIPTION
**Pull request by hueitan**
Phabricator: https://phabricator.wikimedia.org/T286553

 - [x] GitHub Actions Script
 - [x] CI Badge
 - [x] <s>Split job flow for visualization and parellel run test for unit/e2e then deploy in speedy.</s> _make it slower..._
 - [x] <s>Update the message `This branch has not been deployed No deployments`</s> _not possible now_
 - [x] Cleanup `gh-pages` directory manually before merging << Once this PR is reviewed, will do this.
 - [ ] Change the demo link from `demo` to `main` << I don't have permission, so @stephanebisson can do this after this

Please ignore the circleci test fail, it will be removed once merged.

This Repo:
- pages directory: https://github.com/wikimedia/wikipedia-preview/tree/gh-pages
- demo example: https://wikimedia.github.io/wikipedia-preview/T286553-deploy/
- storybook example: https://wikimedia.github.io/wikipedia-preview/T286553-deploy/storybook

Tested Repo:
- pages directory: https://github.com/hueitan/wikipedia-preview/tree/gh-pages-test
- demo example: https://hueitan.github.io/wikipedia-preview/T286553-deploy/
- storybook example: https://hueitan.github.io/wikipedia-preview/T286553-deploy/storybook

### CODE REVIEW

**Comment by medied** [comment]
All links testing well for me 👍

**Review by stephanebisson — APPROVED** [review]

**Comment by hueitan** [comment]
Regards the `Split job flow for visualization and parellel run test for unit/e2e then deploy in speedy.`

The result doesn't run faster, sometimes slower due to the repeated checkout/cache step, benefit only when we have larger test spec and visualization jobs.

Question, should we use this or keep the current flow (one job runs only)? @stephanebisson @medied 

[example link](https://github.com/hueitan/wikipedia-preview/actions/runs/1424933667)
image

**Comment by hueitan** [comment]
Totally forgot this task, what do you see the above question for multiple job runs? @stephanebisson @medied

**Comment by stephanebisson** [comment]
I would not use parallel jobs if not significantly faster because it is more complex.

**Comment by hueitan** [comment]
Ok, we just need to do these then we can merge this pr.

 - [ ] Cleanup gh-pages directory manually before merging << Once this PR is reviewed, will do this.
 - [ ] Change the demo link from demo to main << I don't have permission, so @stephanebisson can do this after this

**Review by stephanebisson — APPROVED** [review]

**Comment by hueitan** [comment]
alright, I think we don't really need to cleanup the gh-pages, as every new pr will have it's own directory, and what we need to do left is updating the the demo link to main folder. @stephanebisson ,then we can merge.

**Pull request merged**
