### PR TITLE
T289471: Include ellipsis in context with bdi text

### PR DESCRIPTION
**Pull request by medied**
https://phabricator.wikimedia.org/T289471

Follow up to #149, this include the ellipsis in context with `<bdi>` text

image

### CODE REVIEW

**Comment by hueitan** [comment]
it works well for me in this form without additional <div><bdi>
image

**Comment by medied** [comment]
You mean replacing the `<div>` directly with a `<bdi>` and nothing else? From my testing I see that messes with the text placement for shorter strings though

image

**Comment by hueitan** [comment]
I got some inspiration from your commit `max-width`, and it works better, i like the simpler way directly with `<bdi>`
image

**Comment by medied** [comment]
Okay that seems to work well, updated now

**Review by hueitan — APPROVED** [review]
Looks good. 
@jpita test is carefully.

**Comment by jpita** [comment]
do we have preview deploying to a branch named test environment like kaios?

**Comment by stephanebisson** [comment]
Not yet

**Comment by jpita** [comment]
can someone merge this?
I messed up with the github permissions and can't merge code right now

**Pull request merged**
